name: gameapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - images/alcool_gasolina/logo.png
    - images/frase_do_dia/logo.png
    - images/jokenpo/papel.png
    - images/jokenpo/pedra.png
    - images/jokenpo/tesoura.png
    - images/jokenpo/padrao.png
    - images/cara_ou_coroa/cara.png
    - images/cara_ou_coroa/coroa.png
    - images/cara_ou_coroa/padrao.gif
    - images/jogo_da_memoria/imagem1.png
    - images/jogo_da_memoria/imagem2.png
    - images/jogo_da_memoria/imagem3.png
    - images/jogo_da_memoria/imagem4.png
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
